
fabric_name: MPLS_FABRIC

underlay_routing_protocol: isis-sr
overlay_routing_protocol: ibgp
fabric_evpn_encapsulation: mpls
custom_structured_configuration_prefix: "custom_"

bgp_as: 65300
bgp_mesh_pes: false

bfd:
  enable: false



# RD/RT Format
overlay_rd_type:
  admin_subfield: overlay_loopback
overlay_rt_type:
  admin_subfield: 65300

# Must use for cEOS/vEOS
bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

isis_area_id: 49.0001
isis_default_is_type: level-2
isis_default_circuit_type: level-2
isis_default_metric: 5
isis_advertise_passive_only: false
isis_instance: CORE
isis_hello_padding: false



design:
  type: mpls

# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1500


p:
  defaults: 
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24

    node_sid_base: 0
    isis_system_id_prefix: '0000.0001'

  nodes:  
    - name: P1
      id: 93
    - name: P2
      id: 94
    - name: P3
      id: 97
    - name: P4
      id: 98

pe:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    virtual_router_mac_address: 02:1C:73:00:DC:00
    node_sid_base: 0
    overlay_address_families: [ vpn-ipv4 ]
    mpls_route_reflectors: [ RR ]
    isis_system_id_prefix: '0000.0001'
    spanning_tree_mode: mstp
  
  nodes:
    - name: BL1-DC1
      id: 91

    - name: BL1-DC2
      id: 95
  

core_interfaces:
  p2p_links_ip_pools:
    - name: core_pool
      ipv4_pool: 10.0.0.0/24

  p2p_links_profiles:
    - name: core_profile
      mtu: 1500
      isis_metric: 50
      ip_pool: core_pool
      isis_circuit_type: level-1

  p2p_links:
    - nodes: [ BL1-DC1, P1 ]
      interfaces: [ Ethernet1, Ethernet1 ]
      profile: core_profile
      id: 41

    - nodes: [ BL1-DC2, P3 ]
      interfaces: [ Ethernet1, Ethernet1 ]
      profile: core_profile
      id: 42

    - nodes: [ BL1-DC1, RR ]
      interfaces: [ Ethernet5, Ethernet1 ]
      profile: core_profile
      id: 43

    - nodes: [ BL1-DC2, RR ]
      interfaces: [ Ethernet5, Ethernet5 ]
      profile: core_profile
      id: 44
    
    - nodes: [ P1, P3 ]
      interfaces: [ Ethernet2, Ethernet2 ]
      profile: core_profile
      id: 45

    - nodes: [ P1, P2 ]
      interfaces: [ Ethernet4, Ethernet4 ]
      profile: core_profile
      id: 46

    - nodes: [ P3, P4 ]
      interfaces: [ Ethernet4, Ethernet4 ]
      profile: core_profile
      id: 47

    - nodes: [ P4, P2 ]
      interfaces: [ Ethernet2, Ethernet2 ]
      profile: core_profile
      id: 48

    - nodes: [ P4, BL1-DC2 ]
      interfaces: [ Ethernet3, Ethernet4 ]
      profile: core_profile
      id: 49


 
rr:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    isis_system_id_prefix: '0000.0001'
    bgp_defaults:
     - 'neighbor MPLS-OVERLAY-PEERS next-hop-unchanged'

  nodes:
    - name: RR
      id: 90

