hostname: H11
ip_routing: true
spanning_tree:
  mode: mstp
ethernet_interfaces:
- name: Ethernet1
  peer: Leaf11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.11.41/24
static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.11.254
  


#interface Ethernet1
#   no switchport
#   ip address 172.16.11.11/24
#
# ip route 0.0.0.0/0 172.16.11.254

