hostname: ISP-3
ip_routing: true

spanning_tree:
  mode: mstp
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
- name: Loopback0
  description: ISP-3_lo0
  shutdown: false
  ip_address: 9.9.9.9/32
ethernet_interfaces:
- name: Ethernet1
  peer: P10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.5.9/31
  vrf: VRF_A
- name: Ethernet4
  peer: P20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.5.11/31
  vrf: VRF_A
router_bgp:
  as: 65002
  router_id: 9.9.9.9
  peer_groups:
    - name: SITE1
      remote_as: 65101
    - name: SITE2
      remote_as: 65201
  vrfs:
    - name: VRF_A
      neighbors:
        - ip_address: 10.1.5.8
          peer_group: SITE1
        - ip_address: 10.1.5.10
          peer_group: SITE2
  address_family_ipv4:
    networks: 
      - prefix: 9.9.9.9/32