custom_hostname: P1
custom_router_isis:
  instance: CORE
  segment_routing_mpls:
    enabled: true
    router_id: 192.168.255.93
  eos_cli: |-
    traffic-engineering
      no shutdown
      is-type level-2
custom_ethernet_interfaces:
  - name: Ethernet1
    eos_cli: |-
      traffic-engineering
  - name: Ethernet2
    eos_cli: |-
      traffic-engineering
  - name: Ethernet3
    eos_cli: |-
      traffic-engineering
      shutdown
  - name: Ethernet4
    eos_cli: |-
      traffic-engineering
  - name: Ethernet5
    eos_cli: |-
      traffic-engineering
  - name: Ethernet6
    eos_cli: |-
      shutdown
custom_router_traffic_engineering:
  #enabled: true
  segment_routing:
  router_id:
    ipv4: 192.168.255.93