custom_hostname: P4

eos_cli: |-


  interface Ethernet 2,3,4
    no switchport
    isis enable CORE
    traffic-engineering
    isis network point-to-point
    isis circuit-type level-2
    no isis hello padding

  router isis CORE
    segment-routing mpls
     router-id 3.3.0.98
      no shutdown
  
  
    traffic-engineering
      no shutdown
      is-type level-2
  
  router traffic-engineering
   segment-routing
   router-id ipv4 3.3.0.98