custom_hostname: PE1
custom_router_traffic_engineering:
  #enabled: true
  router_id:
    ipv4: 192.168.101.21
  segment_routing:
    colored_tunnel_rib: true
    policy_endpoints:
      - address: 192.168.101.23
        colors:
          - value:  500
            binding_sid: 900500
            description: SR-TE-COLOR-500-PATH-FOR-TRAFFIC-TO-PE3
            name: SR-TE-COLOR-500-HIGHEST-BW
            sbfd_remote_discriminator: 192.168.101.23
            path_group:
              - preference: 1
                explicit_null: "none"
                segment_list:
                  - label_stack: 221 305 306 303 224
          - value: 200
            binding_sid: 900200
            description: SR-TE-COLOR-200-PATH-FOR-TRAFFIC-TO-PE3
            name: SR-TE-COLOR-200-PATH-LOWEST-HOPS
            path_group:
              - preference: 1
                explicit_null: "none" 
                segment_list:
                  - label_stack: 221 305 303 224
custom_router_isis:
  instance: CORE
  segment_routing_mpls:
    enabled: true
    router_id: 192.168.0.101.21
  eos_cli: |-
    traffic-engineering
      no shutdown
      is-type level-1
custom_ethernet_interfaces:
  - name: Ethernet1
    eos_cli: |-
      traffic-engineering
  - name: Ethernet2
    eos_cli: |-
      traffic-engineering
  - name: Ethernet3
    eos_cli: |-
      traffic-engineering
#router traffic-engineering
#   segment-routing
#      rib system-colored-tunnel-rib
#      !
#      policy endpoint 192.19.19.70 color 500
#         binding-sid 1000500
#         description SR-TE PATH FOR TRAFFIC TO NYK-lyd570
#         sbfd remote-discriminator 192.19.19.70
#         !
#         path-group preference 1
#           segment-list label-stack 500475 500476 500264 500570

#router isis sr_instance
#   net 49.0001.0001.0001.0007.00
#   router-id ipv4 1.1.0.7
#   is-type level-2
#   log-adjacency-changes
#   !
#   address-family ipv4 unicast
#      timers local-convergence-delay protected-prefixes
#   !
#   segment-routing mpls
#      no shutdown
#   !
#   traffic-engineering
#      no shutdown
#      is-type level-2
