custom_hostname: PE1
custom_router_bgp:
  as: 65001
  neighbors:
    - ip_address: 192.51.81.1
      remote_as:  65000
    - ip_address: 192.51.82.1
      remote_as:  65000
  address_family_ipv4:
    networks:
      - prefix: 192.168.0.81/32
      - prefix: 192.168.101.21/32
    redistribute_routes:
      - source_protocol: connected
custom_eos_cli: |-   
  interface Ethernet4
    description REGION1
    no switchport
    ip address 192.51.81.2/24 
  !
  interface Ethernet5
    description REGION1
    no switchport
    ip address 192.52.81.2/24
  !

