---
- name: Build fabric configuration
  hosts: SITE1_CE, SITE2_CE, Internet
  tasks:
    - name: Generate Device Configurations and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
