cvp_configlets:
  AVD-MPLS_BL1-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending
    range 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname RR\n!\nspanning-tree mode mstp\nspanning-tree mst
    0 priority 32768\n!\nno enable password\nno aaa root\n!\nvrf instance MGMT\n!\ninterface
    Ethernet1\n   description P2P_LINK_TO_P1_Ethernet1\n   no shutdown\n   mtu 1500\n
    \  no switchport\n   ip address 10.0.0.80/31\n   mpls ip\n   isis enable CORE\n
    \  isis circuit-type level-2\n   isis metric 50\n   no isis hello padding\n   isis
    network point-to-point\n!\ninterface Ethernet5\n   description P2P_LINK_TO_RR_Ethernet1\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.84/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Loopback0\n   description
    MPLS_Overlay_peering\n   no shutdown\n   ip address 192.168.255.91/32\n   isis
    enable CORE\n   isis passive\n   node-segment ipv4 index 91\n!\nip virtual-router
    mac-address 02:1c:73:00:dc:00\n!\nip routing\nno ip routing vrf MGMT\n!\nrouter
    bfd\n   multihop interval 300 min-rx 300 multiplier 3\n!\nrouter bgp 65300\n   router-id
    192.168.255.91\n   maximum-paths 4 ecmp 4\n   no bgp default ipv4-unicast\n   neighbor
    MPLS-OVERLAY-PEERS peer group\n   neighbor MPLS-OVERLAY-PEERS remote-as 65300\n
    \  neighbor MPLS-OVERLAY-PEERS update-source Loopback0\n   neighbor MPLS-OVERLAY-PEERS
    bfd\n   neighbor MPLS-OVERLAY-PEERS send-community\n   neighbor MPLS-OVERLAY-PEERS
    maximum-routes 0\n   neighbor 192.168.255.90 peer group MPLS-OVERLAY-PEERS\n   neighbor
    192.168.255.90 description RR\n   !\n   address-family evpn\n   !\n   address-family
    ipv4\n      no neighbor MPLS-OVERLAY-PEERS activate\n   !\n   address-family vpn-ipv4\n
    \     neighbor MPLS-OVERLAY-PEERS activate\n      neighbor default encapsulation
    mpls next-hop-self source-interface Loopback0\n!\nrouter isis CORE\n   net 49.0001.0000.0001.0091.00\n
    \  is-type level-2\n   router-id ipv4 192.168.255.91\n   log-adjacency-changes\n
    \  !\n   address-family ipv4 unicast\n      maximum-paths 4\n   !\n   segment-routing
    mpls\n      no shutdown\n!\nmpls ip\n!\nmanagement api http-commands\n   protocol
    https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\n\ninterface Ethernet1,5\n
    \ no switchport\n  isis enable CORE\n  traffic-engineering\n  isis network point-to-point\n
    \ isis circuit-type level-2\n  no isis hello padding\n\nrouter isis CORE\n  segment-routing
    mpls\n   router-id 192.168.255.90\n    no shutdown\n\n\n  traffic-engineering\n
    \   no shutdown\n    is-type level-2\n\nrouter traffic-engineering\n segment-routing\n
    router-id ipv4 192.168.255.90\n\n\n \n!\nend\n"
  AVD-MPLS_BL1-DC2: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending
    range 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname RR\n!\nspanning-tree mode mstp\nspanning-tree mst
    0 priority 32768\n!\nno enable password\nno aaa root\n!\nvrf instance MGMT\n!\ninterface
    Ethernet1\n   description P2P_LINK_TO_P3_Ethernet1\n   no shutdown\n   mtu 1500\n
    \  no switchport\n   ip address 10.0.0.82/31\n   mpls ip\n   isis enable CORE\n
    \  isis circuit-type level-2\n   isis metric 50\n   no isis hello padding\n   isis
    network point-to-point\n!\ninterface Ethernet4\n   description P2P_LINK_TO_P4_Ethernet3\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.97/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Ethernet5\n   description
    P2P_LINK_TO_RR_Ethernet5\n   no shutdown\n   mtu 1500\n   no switchport\n   ip
    address 10.0.0.86/31\n   mpls ip\n   isis enable CORE\n   isis circuit-type level-2\n
    \  isis metric 50\n   no isis hello padding\n   isis network point-to-point\n!\ninterface
    Loopback0\n   description MPLS_Overlay_peering\n   no shutdown\n   ip address
    192.168.255.95/32\n   isis enable CORE\n   isis passive\n   node-segment ipv4
    index 95\n!\nip virtual-router mac-address 02:1c:73:00:dc:00\n!\nip routing\nno
    ip routing vrf MGMT\n!\nrouter bfd\n   multihop interval 300 min-rx 300 multiplier
    3\n!\nrouter bgp 65300\n   router-id 192.168.255.95\n   maximum-paths 4 ecmp 4\n
    \  no bgp default ipv4-unicast\n   neighbor MPLS-OVERLAY-PEERS peer group\n   neighbor
    MPLS-OVERLAY-PEERS remote-as 65300\n   neighbor MPLS-OVERLAY-PEERS update-source
    Loopback0\n   neighbor MPLS-OVERLAY-PEERS bfd\n   neighbor MPLS-OVERLAY-PEERS
    send-community\n   neighbor MPLS-OVERLAY-PEERS maximum-routes 0\n   neighbor 192.168.255.90
    peer group MPLS-OVERLAY-PEERS\n   neighbor 192.168.255.90 description RR\n   !\n
    \  address-family evpn\n   !\n   address-family ipv4\n      no neighbor MPLS-OVERLAY-PEERS
    activate\n   !\n   address-family vpn-ipv4\n      neighbor MPLS-OVERLAY-PEERS
    activate\n      neighbor default encapsulation mpls next-hop-self source-interface
    Loopback0\n!\nrouter isis CORE\n   net 49.0001.0000.0001.0095.00\n   is-type level-2\n
    \  router-id ipv4 192.168.255.95\n   log-adjacency-changes\n   !\n   address-family
    ipv4 unicast\n      maximum-paths 4\n   !\n   segment-routing mpls\n      no shutdown\n!\nmpls
    ip\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n
    \  vrf MGMT\n      no shutdown\n!\n\ninterface Ethernet1,5\n  no switchport\n
    \ isis enable CORE\n  traffic-engineering\n  isis network point-to-point\n  isis
    circuit-type level-2\n  no isis hello padding\n\nrouter isis CORE\n  segment-routing
    mpls\n   router-id 192.168.255.90\n    no shutdown\n\n\n  traffic-engineering\n
    \   no shutdown\n    is-type level-2\n\nrouter traffic-engineering\n segment-routing\n
    router-id ipv4 192.168.255.90\n!\nend\n"
  AVD-MPLS_P1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range
    1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname P1\n!\nspanning-tree mode none\n!\nno enable password\nno
    aaa root\n!\nvrf instance MGMT\n!\ninterface Ethernet1\n   description P2P_LINK_TO_BL1-DC1_Ethernet1\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.81/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Ethernet2\n   description
    P2P_LINK_TO_P3_Ethernet2\n   no shutdown\n   mtu 1500\n   no switchport\n   ip
    address 10.0.0.88/31\n   mpls ip\n   isis enable CORE\n   isis circuit-type level-2\n
    \  isis metric 50\n   no isis hello padding\n   isis network point-to-point\n!\ninterface
    Ethernet4\n   description P2P_LINK_TO_P2_Ethernet4\n   no shutdown\n   mtu 1500\n
    \  no switchport\n   ip address 10.0.0.90/31\n   mpls ip\n   isis enable CORE\n
    \  isis circuit-type level-2\n   isis metric 50\n   no isis hello padding\n   isis
    network point-to-point\n!\ninterface Loopback0\n   description LSR_Router_ID\n
    \  no shutdown\n   ip address 192.168.255.93/32\n   isis enable CORE\n   isis
    passive\n   node-segment ipv4 index 93\n!\nip routing\nno ip routing vrf MGMT\n!\nrouter
    isis CORE\n   net 49.0001.0000.0001.0093.00\n   is-type level-2\n   router-id
    ipv4 192.168.255.93\n   log-adjacency-changes\n   !\n   address-family ipv4 unicast\n
    \     maximum-paths 4\n   !\n   segment-routing mpls\n      no shutdown\n!\nmpls
    ip\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n
    \  vrf MGMT\n      no shutdown\n!\ninterface Ethernet1,2,4,5\n  no switchport\n
    \ isis enable CORE\n  traffic-engineering\n  isis network point-to-point\n  isis
    circuit-type level-2\n  no isis hello padding\n\nrouter isis CORE\n  segment-routing
    mpls\n   router-id 192.168.255.93\n   no shut\n\n  traffic-engineering\n    no
    shutdown\n    is-type level-2\n\nrouter traffic-engineering\n segment-routing\n
    router-id ipv4 192.168.255.93 \n!\nend\n"
  AVD-MPLS_P2: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range
    1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname P2\n!\nspanning-tree mode none\n!\nno enable password\nno
    aaa root\n!\nvrf instance MGMT\n!\ninterface Ethernet2\n   description P2P_LINK_TO_P4_Ethernet2\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.95/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Ethernet4\n   description
    P2P_LINK_TO_P1_Ethernet4\n   no shutdown\n   mtu 1500\n   no switchport\n   ip
    address 10.0.0.91/31\n   mpls ip\n   isis enable CORE\n   isis circuit-type level-2\n
    \  isis metric 50\n   no isis hello padding\n   isis network point-to-point\n!\ninterface
    Loopback0\n   description LSR_Router_ID\n   no shutdown\n   ip address 192.168.255.94/32\n
    \  isis enable CORE\n   isis passive\n   node-segment ipv4 index 94\n!\nip routing\nno
    ip routing vrf MGMT\n!\nrouter isis CORE\n   net 49.0001.0000.0001.0094.00\n   is-type
    level-2\n   router-id ipv4 192.168.255.94\n   log-adjacency-changes\n   !\n   address-family
    ipv4 unicast\n      maximum-paths 4\n   !\n   segment-routing mpls\n      no shutdown\n!\nmpls
    ip\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n
    \  vrf MGMT\n      no shutdown\n!\n\ninterface Ethernet2,3,4\n   no switchport\n
    \  isis enable CORE\n   traffic-engineering\n   isis network point-to-point\n
    \  isis circuit-type level-2\n   no isis hello padding\n\n router isis CORE\n
    \  segment-routing mpls\n     router-id 192.168.255.94\n     no shutdown\n \n
    \  traffic-engineering\n     no shutdown\n     is-type level-2\n \n router traffic-engineering\n
    \ segment-routing\n  router-id ipv4 192.168.255.94\n \n!\nend\n"
  AVD-MPLS_P3: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range
    1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname P3\n!\nspanning-tree mode none\n!\nno enable password\nno
    aaa root\n!\nvrf instance MGMT\n!\ninterface Ethernet1\n   description P2P_LINK_TO_BL1-DC2_Ethernet1\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.83/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Ethernet2\n   description
    P2P_LINK_TO_P1_Ethernet2\n   no shutdown\n   mtu 1500\n   no switchport\n   ip
    address 10.0.0.89/31\n   mpls ip\n   isis enable CORE\n   isis circuit-type level-2\n
    \  isis metric 50\n   no isis hello padding\n   isis network point-to-point\n!\ninterface
    Ethernet4\n   description P2P_LINK_TO_P4_Ethernet4\n   no shutdown\n   mtu 1500\n
    \  no switchport\n   ip address 10.0.0.92/31\n   mpls ip\n   isis enable CORE\n
    \  isis circuit-type level-2\n   isis metric 50\n   no isis hello padding\n   isis
    network point-to-point\n!\ninterface Loopback0\n   description LSR_Router_ID\n
    \  no shutdown\n   ip address 192.168.255.97/32\n   isis enable CORE\n   isis
    passive\n   node-segment ipv4 index 97\n!\nip routing\nno ip routing vrf MGMT\n!\nrouter
    isis CORE\n   net 49.0001.0000.0001.0097.00\n   is-type level-2\n   router-id
    ipv4 192.168.255.97\n   log-adjacency-changes\n   !\n   address-family ipv4 unicast\n
    \     maximum-paths 4\n   !\n   segment-routing mpls\n      no shutdown\n!\nmpls
    ip\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n
    \  vrf MGMT\n      no shutdown\n!\n\ninterface Ethernet 1,2,3,4\n   no switchport\n
    \  isis enable CORE\n   traffic-engineering\n   isis network point-to-point\n
    \  isis circuit-type level-2\n   no isis hello padding\n\n router isis CORE\n
    \  segment-routing mpls\n    router-id 192.168.255.97\n     no shutdown\n  \n
    \n   traffic-engineering\n     no shutdown\n     is-type level-2\n \n router traffic-engineering\n
    \ segment-routing\n  router-id ipv4 192.168.255.97\n!\nend\n"
  AVD-MPLS_P4: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range
    1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname P4\n!\nspanning-tree mode none\n!\nno enable password\nno
    aaa root\n!\nvrf instance MGMT\n!\ninterface Ethernet2\n   description P2P_LINK_TO_P2_Ethernet2\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.94/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Ethernet3\n   description
    P2P_LINK_TO_BL1-DC2_Ethernet4\n   no shutdown\n   mtu 1500\n   no switchport\n
    \  ip address 10.0.0.96/31\n   mpls ip\n   isis enable CORE\n   isis circuit-type
    level-2\n   isis metric 50\n   no isis hello padding\n   isis network point-to-point\n!\ninterface
    Ethernet4\n   description P2P_LINK_TO_P3_Ethernet4\n   no shutdown\n   mtu 1500\n
    \  no switchport\n   ip address 10.0.0.93/31\n   mpls ip\n   isis enable CORE\n
    \  isis circuit-type level-2\n   isis metric 50\n   no isis hello padding\n   isis
    network point-to-point\n!\ninterface Loopback0\n   description LSR_Router_ID\n
    \  no shutdown\n   ip address 192.168.255.98/32\n   isis enable CORE\n   isis
    passive\n   node-segment ipv4 index 98\n!\nip routing\nno ip routing vrf MGMT\n!\nrouter
    isis CORE\n   net 49.0001.0000.0001.0098.00\n   is-type level-2\n   router-id
    ipv4 192.168.255.98\n   log-adjacency-changes\n   !\n   address-family ipv4 unicast\n
    \     maximum-paths 4\n   !\n   segment-routing mpls\n      no shutdown\n!\nmpls
    ip\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n
    \  vrf MGMT\n      no shutdown\n!\n\ninterface Ethernet 2,3,4\n  no switchport\n
    \ isis enable CORE\n  traffic-engineering\n  isis network point-to-point\n  isis
    circuit-type level-2\n  no isis hello padding\n\nrouter isis CORE\n  segment-routing
    mpls\n   router-id 192.168.255.98\n    no shutdown\n\n\n  traffic-engineering\n
    \   no shutdown\n    is-type level-2\n\nrouter traffic-engineering\n segment-routing\n
    router-id ipv4 192.168.255.98\n!\nend\n"
  AVD-MPLS_RR: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range
    1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols
    model multi-agent\n!\nhostname RR\n!\nspanning-tree mode none\n!\nno enable password\nno
    aaa root\n!\nvrf instance MGMT\n!\ninterface Ethernet1\n   description P2P_LINK_TO_BL1-DC1_Ethernet5\n
    \  no shutdown\n   mtu 1500\n   no switchport\n   ip address 10.0.0.85/31\n   mpls
    ip\n   isis enable CORE\n   isis circuit-type level-2\n   isis metric 50\n   no
    isis hello padding\n   isis network point-to-point\n!\ninterface Ethernet5\n   description
    P2P_LINK_TO_BL1-DC2_Ethernet5\n   no shutdown\n   mtu 1500\n   no switchport\n
    \  ip address 10.0.0.87/31\n   mpls ip\n   isis enable CORE\n   isis circuit-type
    level-2\n   isis metric 50\n   no isis hello padding\n   isis network point-to-point\n!\ninterface
    Loopback0\n   description MPLS_Overlay_peering\n   no shutdown\n   ip address
    192.168.255.90/32\n   isis enable CORE\n   isis passive\n   node-segment ipv4
    index 90\n!\nip routing\nno ip routing vrf MGMT\n!\nrouter bfd\n   multihop interval
    300 min-rx 300 multiplier 3\n!\nrouter bgp 65300\n   router-id 192.168.255.90\n
    \  maximum-paths 4 ecmp 4\n   no bgp default ipv4-unicast\n   bgp cluster-id 192.168.255.90\n
    \  neighbor MPLS-OVERLAY-PEERS next-hop-unchanged\n   neighbor MPLS-OVERLAY-PEERS
    peer group\n   neighbor MPLS-OVERLAY-PEERS remote-as 65300\n   neighbor MPLS-OVERLAY-PEERS
    update-source Loopback0\n   neighbor MPLS-OVERLAY-PEERS route-reflector-client\n
    \  neighbor MPLS-OVERLAY-PEERS bfd\n   neighbor MPLS-OVERLAY-PEERS send-community\n
    \  neighbor MPLS-OVERLAY-PEERS maximum-routes 0\n   neighbor RR-OVERLAY-PEERS
    peer group\n   neighbor RR-OVERLAY-PEERS remote-as 65300\n   neighbor RR-OVERLAY-PEERS
    update-source Loopback0\n   neighbor RR-OVERLAY-PEERS bfd\n   neighbor RR-OVERLAY-PEERS
    send-community\n   neighbor RR-OVERLAY-PEERS maximum-routes 0\n   neighbor 192.168.255.91
    peer group MPLS-OVERLAY-PEERS\n   neighbor 192.168.255.91 description BL1-DC1\n
    \  neighbor 192.168.255.95 peer group MPLS-OVERLAY-PEERS\n   neighbor 192.168.255.95
    description BL1-DC2\n   !\n   address-family evpn\n      neighbor RR-OVERLAY-PEERS
    activate\n   !\n   address-family ipv4\n      no neighbor MPLS-OVERLAY-PEERS activate\n
    \     no neighbor RR-OVERLAY-PEERS activate\n   !\n   address-family vpn-ipv4\n
    \     neighbor MPLS-OVERLAY-PEERS activate\n      neighbor RR-OVERLAY-PEERS activate\n!\nrouter
    isis CORE\n   net 49.0001.0000.0001.0090.00\n   is-type level-2\n   router-id
    ipv4 192.168.255.90\n   log-adjacency-changes\n   !\n   address-family ipv4 unicast\n
    \     maximum-paths 4\n   !\n   segment-routing mpls\n      no shutdown\n!\nmpls
    ip\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n   !\n
    \  vrf MGMT\n      no shutdown\n!\n\ninterface Ethernet1,5\n  no switchport\n
    \ isis enable CORE\n  traffic-engineering\n  isis network point-to-point\n  isis
    circuit-type level-2\n  no isis hello padding\n\nrouter isis CORE\n  segment-routing
    mpls\n   router-id 192.168.255.90\n    no shutdown\n\n\n  traffic-engineering\n
    \   no shutdown\n    is-type level-2\n\nrouter traffic-engineering\n segment-routing\n
    router-id ipv4 192.168.255.90\n!\nend\n"
cvp_topology:
  MPLS_FABRIC:
    devices: []
    parent_container: Tenant
  PE_ROUTERS:
    devices:
    - BL1-DC1
    - BL1-DC2
    parent_container: WAN1
  P_ROUTERS:
    devices:
    - P1
    - P2
    - P3
    - P4
    parent_container: WAN1
  RR_ROUTERS:
    devices:
    - RR
    parent_container: WAN1
  WAN1:
    devices: []
    parent_container: MPLS_FABRIC
